import 'pictogram.dart';

/// A phrase generated by the AI from a sequence of pictograms.
class GeneratedPhrase {
  final String id;
  final List<Pictogram> pictograms;
  final String text;          // The AI-generated natural language phrase
  final DateTime createdAt;
  final bool isFavorite;
  final int usageCount;

  const GeneratedPhrase({
    required this.id,
    required this.pictograms,
    required this.text,
    required this.createdAt,
    this.isFavorite = false,
    this.usageCount = 0,
  });

  GeneratedPhrase copyWith({
    bool? isFavorite,
    int? usageCount,
  }) => GeneratedPhrase(
    id: id,
    pictograms: pictograms,
    text: text,
    createdAt: createdAt,
    isFavorite: isFavorite ?? this.isFavorite,
    usageCount: usageCount ?? this.usageCount,
  );

  Map<String, dynamic> toMap() => {
    'id': id,
    'pictogramIds': pictograms.map((p) => p.id).toList(),
    'pictogramLabels': pictograms.map((p) => p.label).toList(),
    'pictogramEmojis': pictograms.map((p) => p.emoji).toList(),
    'text': text,
    'createdAt': createdAt.toIso8601String(),
    'isFavorite': isFavorite,
    'usageCount': usageCount,
  };
}
